networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - /var/lib/postgresql/data
    networks:
      custom:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      # - mongodata:/var/lib/mongodb/data
      - /var/lib/mongodb/data
    networks:
      custom:
  rabitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      custom:
  auction-svc:
    image: pmuszel/auction-svc:latest
    build: 
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    ports:
      - 7001:80
      - 7777:7777
    networks:
      custom:
    depends_on:
      - postgres
      - rabitmq
  search-svc:
    image: pmuszel/search-svc:latest
    build: 
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongo
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
    networks:
      custom:
    depends_on:
      - mongo
      - rabitmq
  identity-svc:
    image: pmuszel/identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=http://app.carsties.com
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
      - VIRTUAL_HOST=id.carsties.com
    networks:
      custom:
        ipv4_address: 10.5.0.200
    depends_on:
      - postgres
  gateway-svc:
    image: pmuszel/gateway-svc:latest
    build: 
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=https://app.carsties.com
      - VIRTUAL_HOST=api.carsties.com
    networks:
      custom:
  bid-svc:
    image: pmuszel/bid-svc:latest
    build: 
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:mongopw@mongo
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuction=http://auction-svc:7777
    ports:
      - 7003:80
    networks:
      custom:
    depends_on:
      - mongo
      - rabitmq
  notify-svc:
    image: pmuszel/notify-svc:latest
    build: 
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabitmq
    ports:
      - 7004:80
    networks:
      custom:
    depends_on:
      - rabitmq
  web-app:
    image: pmuszel/web-app:latest
    build: 
      context: .
      dockerfile: frontend/web-app/Dockerfile
    volumes:
      - /var/lib/web/data
    networks:
      custom:
    extra_hosts:
      - id.carsties.com:10.5.0.200
    environment:
      - NEXTAUTH_SECRET=somethingrellysecret
      - NEXTAUTH_URL=http://app.carsties.com
      - NEXTAUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gateway-svc/
      - ID_URL=http://id.carsties.com
      - NEXT_PUBLIC_NOTIFY_URL=http://gateway-svc/notifications
      - CLIENT_SECRET=secret
      - VIRTUAL_HOST=app.carsties.com
      - VIRTUAL_PORT=3000

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      custom:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devcerts:/etc/nginx/certs
# volumes:
#   pgdata:
#   mongodata: